import { Geist, Geist_Mono } from "next/font/google";
import { MiniKitProvider } from "@worldcoin/minikit-js/minikit-provider";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MiniKitProvider appId={process.env.NEXT_PUBLIC_APP_ID}>
        <body
          className={`${geistSans.variable} ${geistMono.variable}`}
          suppressHydrationWarning={true}
        >
          {children}
        </body>
      </MiniKitProvider>
    </html>
  );
}
